language: go
go:
  - 1.1
before_script:
  - mysql -e 'create database db_test;'
  - go get github.com/acsellers/assert
  - go get github.com/acsellers/inflections
  - go get github.com/go-sql-driver/mysql
  - go get code.google.com/p/go-sqlite/go1/sqlite3
env: CI=yes
